package com.dsf.bysj.model;

/**
 * TZulin generated by MyEclipse Persistence Tools
 */

public class TZulin implements java.io.Serializable
{

	private Integer id;
	private int cheId;
	private int userId;
	private String kaishishijian;
	
	private Integer yajin;
	private String beizhu;
	private String shifouhuan;
	private String jieshushijian;
	
	private Integer feiyong;
	
	private TChe che;

	public Integer getId()
	{
		return id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public int getCheId()
	{
		return cheId;
	}

	public void setCheId(int cheId)
	{
		this.cheId = cheId;
	}

	public int getUserId()
	{
		return userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}

	public String getKaishishijian()
	{
		return kaishishijian;
	}

	public void setKaishishijian(String kaishishijian)
	{
		this.kaishishijian = kaishishijian;
	}

	public Integer getYajin()
	{
		return yajin;
	}

	public void setYajin(Integer yajin)
	{
		this.yajin = yajin;
	}

	public String getBeizhu()
	{
		return beizhu;
	}

	public void setBeizhu(String beizhu)
	{
		this.beizhu = beizhu;
	}

	public String getShifouhuan()
	{
		return shifouhuan;
	}

	public void setShifouhuan(String shifouhuan)
	{
		this.shifouhuan = shifouhuan;
	}

	public String getJieshushijian()
	{
		return jieshushijian;
	}

	public void setJieshushijian(String jieshushijian)
	{
		this.jieshushijian = jieshushijian;
	}

	public Integer getFeiyong()
	{
		return feiyong;
	}

	public void setFeiyong(Integer feiyong)
	{
		this.feiyong = feiyong;
	}

	public TChe getChe()
	{
		return che;
	}

	public void setChe(TChe che)
	{
		this.che = che;
	}

}